#
# youtube-dl Server Dockerfile
#
# https://github.com/nbr23/youtube-dl-server
#

FROM alpine as ffmpeg

WORKDIR /ffmpeg

RUN apk add wget &&  \
  if [ "$(uname -m)" == "x86_64" ]; then \
  wget https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz; \
  elif [ "$(uname -m)" == "aarch64" ]; then \
  wget https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-arm64-static.tar.xz; \
  elif [ "$(uname -m)" == "armv7l" ]; then \
  wget https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-armhf-static.tar.xz; \
  else \
  wget https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-$(uname -m)-static.tar.xz; \
  fi \
  && tar -xvf ffmpeg-git-*-static.tar.xz && cd ffmpeg-git-*-static && mv ffmpeg ffprobe ../

FROM python:alpine3.17
ARG YOUTUBE_DL=yt_dlp
ARG ATOMICPARSLEY=0

VOLUME "/youtube-dl"
VOLUME "/app_config"

COPY --from=nbr23/youtube-dl-wheels /out/wheels /wheels
RUN pip install --upgrade --no-cache-dir pip && pip install --no-cache-dir /wheels/*

RUN mkdir -p /usr/src/app
COPY --from=ffmpeg /ffmpeg/ffmpeg /usr/local/bin/ffmpeg
COPY --from=ffmpeg /ffmpeg/ffprobe /usr/local/bin/ffprobe
RUN apk add --no-cache tzdata mailcap
RUN if [ $ATOMICPARSLEY == 1 ]; then apk add --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing atomicparsley; ln /usr/bin/atomicparsley /usr/bin/AtomicParsley || true; fi
COPY ./requirements-yt-dlp.txt /usr/src/app/
RUN pip install --upgrade pip && pip install --no-cache-dir -r /usr/src/app/requirements-yt-dlp.txt

COPY ./bootstrap.sh /usr/src/app/
COPY ./docker_run.sh /usr/src/app/
COPY ./config.yml /usr/src/app/default_config.yml
COPY ./ydl_server /usr/src/app/ydl_server
COPY ./youtube-dl-server.py /usr/src/app/

WORKDIR /usr/src/app

RUN apk add --no-cache wget && ./bootstrap.sh && apk del wget


EXPOSE 8080

ENV YOUTUBE_DL=$YOUTUBE_DL
ENV YDL_CONFIG_PATH='/app_config'
CMD [ "./docker_run.sh" ]
